-- Schema reference for public.profiles (documentation only, not executed)
-- See supabase/migrations/20260821000000_create_profiles.sql for the migration

-- Table: public.profiles
-- Columns:
--   id           uuid        PK, FK -> auth.users(id) ON DELETE CASCADE
--   display_name text        nullable
--   avatar_url   text        nullable
--   created_at   timestamptz not null, default now()
--   updated_at   timestamptz not null, default now()
--
-- RLS: enabled
-- Policies:
--   SELECT: anyone (public read)
--   INSERT: authenticated, auth.uid() = id
--   UPDATE: authenticated, auth.uid() = id
--   DELETE: authenticated, auth.uid() = id
--
-- Trigger: on_auth_user_created -> handle_new_user()
--   Auto-creates profile row with display_name from signup metadata or email prefix
