-- Schema reference for public.subscribers (documentation only, not executed)
-- Migration: 20260822000000_content_tables.sql

-- Table: public.subscribers
-- Columns:
--   id            uuid        PK, default gen_random_uuid()
--   email         text        not null, unique
--   subscribed_at timestamptz not null, default now()
--   active        boolean     not null, default true
--
-- RLS: enabled
-- Grants:
--   anon: SELECT, INSERT
--   authenticated: SELECT
--   service_role: ALL
-- Policies:
--   SELECT: anyone (public read)
--   INSERT: anon (public can subscribe)
--   ALL: authenticated + is_admin() (admin write)
